# lista_excel_files.yaml
jobs:
  - name: rep_plr
    src_dir: 'C:\data\SAP_Extraction\rep_plr'
    out_dir: 'C:\data\SAP_Extraction\rep_plr\output'
    ref: 'C:\data\SAP_Extraction\rep_plr\plantilla\REP_PLR_FINAL.xlsx'
    pattern: 'REP_PLR-*.xlsx'
    header_row: 5
    keep_extras: true
    date_cols: ['Fe.Entrega', 'Fecha Guía', 'Creado el']
    suffix: '_REORDENADO'

  - name: y_dev_45
    src_dir: 'C:\data\SAP_Extraction\y_dev_45'
    out_dir: 'C:\data\SAP_Extraction\y_dev_45\output'
    ref: 'C:\data\SAP_Extraction\y_dev_45\plantilla\y_dev_45_final.xlsx'
    pattern: 'y_dev_45_*.xlsx'
    start_col: 'B'
    header_row: 3
    keep_extras: true
    date_cols: ['Fecha','Reprogramado']
    suffix: '_REORDENADO'

  - name: y_dev_74
    src_dir: 'C:\data\SAP_Extraction\y_dev_74'
    out_dir: 'C:\data\SAP_Extraction\y_dev_74\output'
    ref: 'C:\data\SAP_Extraction\y_dev_74\plantilla\y_dev_74_final.xlsx'   # <- ajustado
    pattern: 'y_dev_74_*.xlsx'
    start_col: 'B'
    header_row: 3
    keep_extras: true
    date_cols: ['F. Proceso', 'F. Creado', 'Carga HHD']
    suffix: '_REORDENADO'

  - name: y_dev_82
    src_dir: 'C:\data\SAP_Extraction\y_dev_82'
    out_dir: 'C:\data\SAP_Extraction\y_dev_82\output'
    ref: 'C:\data\SAP_Extraction\y_dev_82\plantilla\y_dev_82_final.xlsx'   # <- ajustado
    pattern: 'y_dev_82_*.xlsx'
    start_col: 'B'
    header_row: 3
    keep_extras: true
    date_cols: ['Fecha']
    suffix: '_REORDENADO'

  - name: z_devo_alv
    src_dir: 'C:\data\SAP_Extraction\z_devo_alv'
    out_dir: 'C:\data\SAP_Extraction\z_devo_alv\output'
    ref: 'C:\data\SAP_Extraction\z_devo_alv\plantilla\z_devo_alv_final.xlsx'  # <- ajustado
    pattern: 'z_devo_alv_*.xlsx'
    header_row: 5
    keep_extras: true
    date_cols: ['Fecha']
    suffix: '_REORDENADO'

  - name: zhbo
    src_dir: 'C:\data\SAP_Extraction\zhbo'
    out_dir: 'C:\data\SAP_Extraction\zhbo\output'
    ref: 'C:\data\SAP_Extraction\zhbo\plantilla\zhbo_final.xlsx'  # <- ajustado
    pattern: 'zhbo_*.xlsx'
    header_row: 6
    keep_extras: true
    date_cols: ['Fecha Doc', 'Fecha Entrega', 'Fecha Cambio Estado']
    suffix: '_REORDENADO'

  - name: zred
    src_dir: 'C:\data\SAP_Extraction\zred'
    out_dir: 'C:\data\SAP_Extraction\zred\output'
    ref: 'C:\data\SAP_Extraction\zred\plantilla\zred_final.xlsx'  # <- ajustado
    pattern: 'zred_*.xlsx'
    header_row: 5
    keep_extras: true
    date_cols: ['Fecha']
    suffix: '_REORDENADO'

  - name: Zresguias
    src_dir: 'C:\data\SAP_Extraction\Zresguias'
    out_dir: 'C:\data\SAP_Extraction\Zresguias\output'
    ref: 'C:\data\SAP_Extraction\Zresguias\plantilla\zresguias_final.xlsx'  # <- ajustado
    pattern: 'zresguias_*.xlsx'
    header_row: 5
    keep_extras: true
    date_cols: ['Fecha']
    suffix: '_REORDENADO'

  - name: zsd_incidencias
    src_dir: 'C:\data\SAP_Extraction\zsd_incidencias'
    out_dir: 'C:\data\SAP_Extraction\zsd_incidencias\output'
    ref: 'C:\data\SAP_Extraction\zsd_incidencias\plantilla\zsd_incidencias_final.xlsx'  # <- ajustado
    pattern: 'zsd_incidencias_*.xlsx'
    header_row: 5
    keep_extras: true
    date_cols: ['Fe.Entrega', 'Fecha Guía', 'Creado el']
    suffix: '_REORDENADO'